models:
  - name: "particlenet_AK4_PT"
    version: "1"
    platform: "pytorch_libtorch"
    inputs:
      - name: "pf_points"
        dtype: "FP32"
        shape: [2, 100]
      - name: "pf_features"
        dtype: "FP32"
        shape: [20, 100]
      - name: "pf_mask"
        dtype: "FP32"
        shape: [1, 100]
      - name: "sv_points"
        dtype: "FP32"
        shape: [2, 10]
      - name: "sv_features"
        dtype: "FP32"
        shape: [11, 10]
      - name: "sv_mask"
        dtype: "FP32"
        shape: [1, 10]

  - name: "particlenet_AK4"
    version: "1"
    platform: "onnxruntime"
    inputs:
      - name: "pf_points"
        dtype: "FP32"
        shape: [2, 100]
      - name: "pf_features"
        dtype: "FP32"
        shape: [20, 100]
      - name: "pf_mask"
        dtype: "FP32"
        shape: [1, 100]
      - name: "sv_points"
        dtype: "FP32"
        shape: [2, 10]
      - name: "sv_features"
        dtype: "FP32"
        shape: [11, 10]
      - name: "sv_mask"
        dtype: "FP32"
        shape: [1, 10]

runs:
  - name: "Run1"
    stages:
      - client_sequences:
        - steps:
          - model_name: "particlenet_AK4_PT"
            batch_size: 8
            stop_value: 100
            stop_condition: "NUM_TRIALS"

          - model_name: "particlenet_AK4_PT"
            batch_size: 16
            stop_value: 100
            stop_condition: "NUM_TRIALS"

          - model_name: "particlenet_AK4_PT"
            batch_size: 32
            stop_value: 100
            stop_condition: "NUM_TRIALS"

          - model_name: "particlenet_AK4_PT"
            batch_size: 64
            stop_value: 100
            stop_condition: "NUM_TRIALS"

          - model_name: "particlenet_AK4_PT"
            batch_size: 128
            stop_value: 100
            stop_condition: "NUM_TRIALS"

          - model_name: "particlenet_AK4_PT"
            batch_size: 256
            stop_value: 100
            stop_condition: "NUM_TRIALS"
