# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NereidStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/inference.Nereid/HealthCheck',
                request_serializer=inference__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ViewModels = channel.unary_unary(
                '/inference.Nereid/ViewModels',
                request_serializer=inference__pb2.ViewModelsRequest.SerializeToString,
                response_deserializer=inference__pb2.ViewModelsResponse.FromString,
                _registered_method=True)
        self.Checkpoint = channel.stream_stream(
                '/inference.Nereid/Checkpoint',
                request_serializer=inference__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=inference__pb2.CheckpointResponse.FromString,
                _registered_method=True)


class NereidServicer:
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkpoint(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NereidServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inference__pb2.HealthCheckRequest.FromString,
                    response_serializer=inference__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ViewModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewModels,
                    request_deserializer=inference__pb2.ViewModelsRequest.FromString,
                    response_serializer=inference__pb2.ViewModelsResponse.SerializeToString,
            ),
            'Checkpoint': grpc.stream_stream_rpc_method_handler(
                    servicer.Checkpoint,
                    request_deserializer=inference__pb2.CheckpointRequest.FromString,
                    response_serializer=inference__pb2.CheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.Nereid', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.Nereid', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Nereid:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.Nereid/HealthCheck',
            inference__pb2.HealthCheckRequest.SerializeToString,
            inference__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.Nereid/ViewModels',
            inference__pb2.ViewModelsRequest.SerializeToString,
            inference__pb2.ViewModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkpoint(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.Nereid/Checkpoint',
            inference__pb2.CheckpointRequest.SerializeToString,
            inference__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
