# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x13\n\x11ViewModelsRequest\")\n\x12ViewModelsResponse\x12\x13\n\x0bmodel_names\x18\x01 \x03(\t\"r\n\x11\x43heckpointRequest\x12)\n\x04meta\x18\x01 \x01(\x0b\x32\x19.inference.CheckpointMetaH\x00\x12\'\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x16.inference.TensorChunkH\x00\x42\t\n\x07payload\"9\n\x0e\x43heckpointMeta\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\"k\n\x0bTensorChunk\x12\x13\n\x0btensor_name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x04 \x01(\x04\x12\x15\n\rend_of_tensor\x18\x05 \x01(\x08\"r\n\x12\x43heckpointResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\x11\n\texit_code\x18\x03 \x01(\x05\x12,\n\x0coutput_chunk\x18\x04 \x01(\x0b\x32\x16.inference.TensorChunk\"C\n\x14ModelInferenceConfig\x12\x13\n\x0binput_shape\x18\x01 \x03(\x03\x12\x16\n\x0emax_batch_size\x18\x02 \x01(\x03\x32\xf0\x01\n\x06Nereid\x12L\n\x0bHealthCheck\x12\x1d.inference.HealthCheckRequest\x1a\x1e.inference.HealthCheckResponse\x12I\n\nViewModels\x12\x1c.inference.ViewModelsRequest\x1a\x1d.inference.ViewModelsResponse\x12M\n\nCheckpoint\x12\x1c.inference.CheckpointRequest\x1a\x1d.inference.CheckpointResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=30
  _globals['_HEALTHCHECKREQUEST']._serialized_end=50
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=52
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=89
  _globals['_VIEWMODELSREQUEST']._serialized_start=91
  _globals['_VIEWMODELSREQUEST']._serialized_end=110
  _globals['_VIEWMODELSRESPONSE']._serialized_start=112
  _globals['_VIEWMODELSRESPONSE']._serialized_end=153
  _globals['_CHECKPOINTREQUEST']._serialized_start=155
  _globals['_CHECKPOINTREQUEST']._serialized_end=269
  _globals['_CHECKPOINTMETA']._serialized_start=271
  _globals['_CHECKPOINTMETA']._serialized_end=328
  _globals['_TENSORCHUNK']._serialized_start=330
  _globals['_TENSORCHUNK']._serialized_end=437
  _globals['_CHECKPOINTRESPONSE']._serialized_start=439
  _globals['_CHECKPOINTRESPONSE']._serialized_end=553
  _globals['_MODELINFERENCECONFIG']._serialized_start=555
  _globals['_MODELINFERENCECONFIG']._serialized_end=622
  _globals['_NEREID']._serialized_start=625
  _globals['_NEREID']._serialized_end=865
# @@protoc_insertion_point(module_scope)
